In [1]:
import numpy as np

In [2]:
x = np.array([5,150,150,5])
y = np.array([5,5,150,150])
xp = np.array([150,150,220,80])
yp = np.array([5,150,100,200])


In [54]:
A = np.array([[-x[0],-y[0],-1,0,0,0,x[0]*xp[0],y[0]*xp[0],xp[0]],
              [0,0,0,-x[0],-y[0],-1,x[0]*yp[0],y[0]*yp[0],yp[0]],
              [-x[1],-y[1],-1,0,0,0,x[1]*xp[1],y[1]*xp[1],xp[1]],
              [0,0,0,-x[1],-y[1],-1,x[1]*yp[1],y[1]*yp[1],yp[1]],
              [-x[2],-y[2],-1,0,0,0,x[2]*xp[2],y[2]*xp[2],xp[2]],
              [0,0,0,-x[2],-y[2],-1,x[2]*yp[2],y[2]*yp[2],yp[2]],
              [-x[3],-y[3],-1,0,0,0,x[3]*xp[3],y[3]*xp[3],xp[3]],
              [0,0,0,-x[3],-y[3],-1,x[3]*yp[3],y[3]*yp[3],yp[3]]])

In [55]:
A

array([[   -5,    -5,    -1,     0,     0,     0,   750,   750,   150],
       [    0,     0,     0,    -5,    -5,    -1,    25,    25,     5],
       [ -150,    -5,    -1,     0,     0,     0, 22500,   750,   150],
       [    0,     0,     0,  -150,    -5,    -1, 22500,   750,   150],
       [ -150,  -150,    -1,     0,     0,     0, 33000, 33000,   220],
       [    0,     0,     0,  -150,  -150,    -1, 15000, 15000,   100],
       [   -5,  -150,    -1,     0,     0,     0,   400, 12000,    80],
       [    0,     0,     0,    -5,  -150,    -1,  1000, 30000,   200]])

In [73]:
def compute_SVD(A):
    A_t = A.T
    AA_t = A.dot(A_t)
    U_eig, U_eigv = np.linalg.eig(AA_t)
    
    A_tA = A_t.dot(A)
    V_eig, V_eigv = np.linalg.eig(A_tA)
    V_eigv_t = V_eigv.T
    
    temp = np.array(np.diag((np.sqrt(U_eig))))
    sigma = np.zeros_like(A)
    sigma[:temp.shape[0],:temp.shape[1]] = temp
    H = V_eigv[:,8]
    H = np.reshape(H,(3,3))
    return V_eigv_t, U_eigv, sigma, H
    

In [74]:
VT, U, S, H = compute_SVD(A)

In [75]:
VT

array([[ 2.54946062e-03,  2.25621498e-03,  1.95578817e-05,
         1.54140150e-03,  1.76252703e-03,  1.60004644e-05,
        -7.03055489e-01, -7.11097216e-01, -6.05432678e-03],
       [ 2.41475718e-03, -1.15080213e-03,  7.90192029e-06,
         2.32844267e-03, -3.08269028e-03, -4.98322910e-06,
        -7.11107330e-01,  7.03067767e-01,  1.58511101e-05],
       [-3.55867233e-01, -4.16519208e-01, -2.86986478e-03,
         5.99439572e-01,  5.40128708e-01,  5.25610583e-03,
         4.96133747e-04,  1.43036596e-03, -2.20828633e-01],
       [ 1.97939546e-01, -2.69085083e-02,  5.80620960e-03,
        -2.21957585e-01, -3.39219887e-02,  2.35464817e-04,
         4.14749580e-03,  4.07882439e-03, -9.53736018e-01],
       [-4.09271582e-01,  7.29257605e-01,  3.40947867e-03,
         4.34592174e-01, -2.70145114e-01,  1.04129989e-03,
         1.40815060e-03,  1.40423644e-03, -1.97014502e-01],
       [-5.30421539e-01, -5.09602196e-01, -8.94743600e-03,
        -8.45230599e-02, -6.70064960e-01,  8.028514

In [76]:
H

array([[ 2.31013353e-01, -6.16035605e-02, -8.47048990e-01],
       [ 2.31013353e-01, -1.54008902e-01, -3.85022260e-01],
       [ 1.54008902e-03, -7.70044507e-04, -3.85022271e-03]])